name: CI
on:
    push:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

        - name: Deploying and Running ttyd
          run: |
             sudo apt-get install parallel
             npm install -g localtunnel
             parallel -u ::: 'docker run --rm -p 6969:6969 wettyoss/wetty -p 6969 ' 'lt --port 6969 --subdomain amirulandalib'
