name: CI
on:
    push:
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

        - name: Deploying and Running bot
          run: |
             sudo apt-get install build-essential cmake git libjson-c-dev libwebsockets-dev
             git clone https://github.com/tsl0922/ttyd.git
             cd ttyd && mkdir build && cd build
             cmake ..
             make && sudo make install
             npm install -g localtunnel
             lt --port 6969 --subdomain amirulandalib && ttyd -p 6969 -c abcd:abcd

